[package]
name = "ti-tmp12x-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "ti_tmp12x_rs"
path = "src/lib.rs"

[dependencies]
defmt = "0.3"
embedded-hal = { version = "1", features = ["defmt-03"] }
